### ISSUE TITLE
Error on Myo With EMG example code

### ISSUE THREAD

**Issue by herjunodimas** [nok/myo-processing#2]
Hi, I get this error :

 "# Myo v0.8.0.2 - Support: Myo SDK v0.8.0, Firmware v1.1.5 - https://github.com/voidplus/myo-processing A library relies on native code that's not available. Or only works properly when the sketch is run as a 32-bit  application."

when I run the code using Processing 2.2.1 X64 on Windows 7 64 bit

Is the problem about the java library??

Thanks :D

**Comment by nok** [comment]
Hello @herjunodimas,

thank you. I [pulled and recompiled](https://github.com/NicholasAStuart/myo-java) the dependencies in a [seperate branch](https://github.com/voidplus/myo-processing/tree/0.8.0-3). Git shows no changes of compiled dll`s between version 0.7.1 and 0.8.0. But I guess their should be one. I will mention @NicholasAStuart.

Happy coding,
Darius

**Comment by NicholasAStuart** [comment]
@voidplus Are you saying there's no difference between my DLL's or yours?

**Comment by nok** [comment]
Hello @NicholasAStuart , I have checked it again with the result, that it was my mistake. The fix is [merged](https://github.com/voidplus/myo-processing/commit/74e73501f00e94171dcedc863289380a4273c352#diff-48).

Sorry and thank you @NicholasAStuart for your great work, it's amazing.
@herjunodimas You can update the library and test it again.

Happy coding,
Darius
