### ISSUE TITLE
Which are the ranges of getOrientation()?

### ISSUE THREAD

**Issue by kaosmos** [nok/myo-processing#6]
Hello,
first of all thank you for your library I'm playing with it since I received my Myo armband.
Right now I'm trying to get the roll to control something so I'm using getOrientation() to store the data in a PVector and then I retrieve the roll with PVector.x and now I'm wondering: between which range of values the 3 float value of getOrientation() changes? I thought it was between 0 and 16 but then I saw sometimes they value 17 or even more and I can't find this info in your documentation.
Thank you in advance for your answer.

**Comment by nok** [comment]
Hello @kaosmos ,

my apologies for the long delay here.

There was a scalar of _18_. I removed it ([aa68439](https://github.com/nok/myo-processing/commit/aa684397dc26843d5a3b9215bdf819799e7f4ab6#diff-ca5a227fe97ce2c1f6aacecfbd2479a8)), because it didn't make sense. Thanks for your attention.

With the newest update (_0.8.1.4_) their is a range between 0 and 1. With it you can map it via Processing: `map(orientation.x, 0, 1, 0, 360);`. Just update the library manually or use the updater of the PDE.

Happy coding,
Darius

**Comment by kaosmos** [comment]
Thank you for the answer, Darius, and don't worry about the long delay, as you can see I'm pretty used to practice it too :)
I agree, the new implementation you did is way more straight forward than before, good job!
Thank you again for sharing your lib to the rest of us.
