### ISSUE TITLE
Multiple Myos

### ISSUE THREAD

**Issue by ghost** [nok/myo-processing#7]
I'm wondering if it's possible to use multiple myos with this library.  It seems possible but I can't seem to figure it out.  I'm really enjoying this library so far though. Great Work!

**Comment by nok** [comment]
Hello @twonb1tc4 ,

with the following commits ([e29a69c](https://github.com/nok/myo-processing/commit/e29a69c653a5bd6208d4784e813170200fb10ae1) and [14b1ea9](https://github.com/nok/myo-processing/commit/14b1ea9314c0c5cb95c356ef555dde36ec0b8771)) it should work. Just update to the newest version.

You can use `myo.getId()` to identify/distinguish the devices.

Happy coding,
Darius

**Comment by ghost** [comment]
Both of my Myos are registering as device number 1.  Myos are fully up to date

**Comment by nok** [comment]
Okay, thanks for your response.

I pushed a small [change](https://github.com/nok/myo-processing/commit/be29885b11a3bfa62f32fbd42862b43af0c40ef5#diff-ca5a227fe97ce2c1f6aacecfbd2479a8). Please update and try again.

Happy coding,
Darius

**Comment by ghost** [comment]
Thank you so much for responding so quickly. I really appreciate it

They're still both registering as device number 1.

**Comment by nok** [comment]
Hello @twonb1tc4 ,

do you use one instance of class `Myo`? For example:

```
import de.voidplus.myo.*;

Myo myo;

void setup() {
  size(800, 500);
  background(255);
  // ...

  myo = new Myo(this);
}

void draw() {
  background(255);
  // ...
}

void myoOn(Myo.Event event, Myo myo, long timestamp) {
  println(myo.getId());
}
```

I just want to validate it (, because there is no singleton pattern implemented). In the callback `myoOn` you have access to the ID of one device. I double checked the code and it should work ... but there could be an bug in the native library too.

Thanks for your support and contribution. Each test is valuable.

Happy coding,
Darius

**Comment by ghost** [comment]
Yea I'm only using one instance.  When I run the code you posted I just get a constant stream of ones.  Is there something I should be doing?  Still fairly new to the coding world.

**Comment by ghost** [comment]
I've been testing and it seems like whenever the second myo connects, it takes on the attributes of the first.  If I connect my right armband first, they both return myo.isArmLeft() as false.

**Comment by nok** [comment]
Okay, thank you. I have to consult one's pillow ... it seems that I have to refactor the code a size larger.

**Comment by nok** [comment]
Hello @twonb1tc4 ,

I refactored and revised the library the last few days. Could you please [download that library](https://github.com/nok/myo-processing/blob/dev/download/MyoForProcessing.zip?raw=true) (from **development** branch), install and test it again with the new example `e4_multiple.pde`?

I changed a lot, because of that I didn't push it to the master branch.

Thanks for your help, happy coding,
Darius

**Comment by ghost** [comment]
It works!!!  One quick note, my primary Myo registers as device 0 and the other registers as device 2.  Just a minor thing.  

myo.getId() only works for the example you provided.  The rest don't work.

Thank you \* 1000000

**Comment by nok** [comment]
Step by step ... :-)

Yes, I changed the first ID to 0, because it was easier to handle the devices internally. But it shouldn't increment the ID by 2. Could you please copy the following snippet to the `draw()` method and test it again:

``` java
if(myo.hasDevices()){
  println("Size: " + myo.getDevices().size());
  for(Device device : myo.getDevices()){
    println("# " + device.getId();
  }
}
```

I'm glad that it works generally. If you want to use multiple devices, you have to use specific callbacks, i.e.:

Single device:
`void myoOnPose(Myo myo, long timestamp, Pose pose) { … }`

Multiple devices:
`void myoOnPose(Device myo, long timestamp, Pose pose) { … }`

Because of that the first three examples don't work with multiple devices. I didn't delete the first kind of callbacks in respect of backwards compatibility and the auto updating of the contributed libraries in the Processing environment. The most people have just one device, I guess.

But currently there are some side effects ... with the single and multiple handling.

Happy coding,
Darius

**Comment by ghost** [comment]
I appreciate all the time you have dedicated.

It's saying I have three Myos. 

Other than that things are running very smoothly, as far as I can tell.

**Comment by ghost** [comment]
I can't seem to get the other examples to work, using either Device or Myo.  Even when I have only one Myo connected.

Edit: I worked through the old examples. I see now.

Also, could you possibly provide an example to set the unlock mode to hold? Not entirely sure how the unlock messages get sent.

**Comment by nok** [comment]
Good hints, thank you, I noticed it.

Few minutes ago I improved the emg data handling. Just [download](https://github.com/nok/myo-processing/blob/dev/download/MyoForProcessing.zip?raw=true) the newest version of the **development** branch again.

Now, you can enable or disable the emg data events with `.withEmg()` globally. And I removed the possibility to toggle the emg data handler for each single device. So it works automatically.

Happy coding,
Darius

**Comment by ghost** [comment]
Sorry I haven't been responding.  Things appear to be working well.  Still getting the ID issue but it's not a problem.

I tweeted this at you, but here is project thus far: https://youtu.be/mH6LcjDq8aw

Thank you so much for the time you dedicated to doing this.  I couldn't have gotten this far without you.

**Comment by balandinodidonato** [comment]
Hi @nok, Many thanks for sharing your work.

I can get data from both my Myos except from EMG data.

To do that I just added the following code to the the function `void myoOn(Myo.Event event, Device myo, long timestamp)`.

```
case EMG:
     println("myoOn EMG & Device: "+myo.getId());
    // int[] data <- 8 values from -128 to 127
    int[] data = myo.getEmg();
    for(int i = 0; i<data.length; i++){
      println("emg"+data[i]); // [-128 - 127] 
    }
    break;
```

I also tried:

```
 case EMG:
    println("Myo["+myo.getId()+"] - orienation: "+myo.getEmg());
    break;
```

Have you got any advice for me?

**Comment by balandinodidonato** [comment]
In addition adding `myo.withEmg()` I get these errors back:

```
java.lang.NullPointerException
    at de.voidplus.myo.Device.withEmg(Device.java:133)
    at de.voidplus.myo.Myo.pre(Myo.java:125)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1236)
    at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1229)
    at processing.core.PApplet.handleMethods(PApplet.java:1423)
    at processing.core.PApplet.handleDraw(PApplet.java:2377)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
    at processing.core.PApplet.run(PApplet.java:2256)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by balandinodidonato** [comment]
@twonb1tc4 any good in having EMG data from multiple Myos?

**Comment by nok** [comment]
Hello @balandinodidonato,

you just have to call `withEmg()` on the global instance of class `Myo`.
Please try the following example: https://gist.github.com/nok/62a59a481291f04ad7af

Happy coding,
Darius

**Comment by balandinodidonato** [comment]
With one Myo only it works, but not using two Myos.

**Comment by nok** [comment]
Quick notice: Since last week I had two Myo devices. Next week I will start fixing and extending the functionality of the library.

**Comment by balandinodidonato** [comment]
@nok that's an amzing news nok! many thanks for that!!!

**Comment by nok** [comment]
Hello @twonb1tc4 and @balandinodidonato,

after a long time I found the time for the improvements and changes. In addition I changed some callback names to improve the simplicity. After all it looks and works fine for me.

Try it, destroy it, have fun. 😄 

Happy coding,
Darius
