### ISSUE TITLE
Why Processing?

### ISSUE THREAD

**Issue by ghost** [nok/myo-processing#8]
Hi Darius,

I'm interested in streaming emg data from multiple myos on one arm.
I noticed you've been working on a project that can enable me to do this.
However, I'm not familiar with Processing, and all of the other work necessary
for my project I've done in C++.
Is there a particular reason why you chose Processing? Could I do what you did using
C++ and the SDK that Thalmic Labs provided? I've read a few times that emg streaming
from multiple myos is not supported by the SDK. 

Thanks!

**Comment by nok** [comment]
Hello @mrbaba ,

in your position in this case I wouldn't swap between two different programming languages. Because Processing is based on Java internally.

So I recommend having a look at the basic [emg-data-sample_8cpp-example](https://developer.thalmic.com/docs/api_reference/platform/emg-data-sample_8cpp-example.html) provided by Thalmic Labs.

Happy coding,
Darius
